spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_test
    username: root
    password: admin

mybatis:
  config-locations:
    classpath: mybatis/mybatis-config.xml
  mapper-locations:
    classpath: mybatis/mapper/*.xml