server:
  port: 3333

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzz_test
    username: root
    password: admin

mybatis:
  mapper-locations: "classpath:mybatis/mapper/*.xml"  #classpath*:mybatis*/**/*.xml
  config-location: "classpath:mybatis-config.xml"


# 日志配置
logging:
  level:
    com.example: debug

props:
  sql.show: true

